@host = http://localhost:8080
# Для удалённого сервера:
# @host = https://example.com:444
@app = /currency-exchange
@baseUrl = {{host}}{{app}}

### Получить все валюты
GET {{baseUrl}}/currencies
Accept: application/json

### Получить валюту по коду
GET {{baseUrl}}/currency/USD
Accept: application/json

### Добавить валюту
POST {{baseUrl}}/currencies
Content-Type: application/x-www-form-urlencoded
Accept: application/json

name=Australian dollar&code=AUD&sign=A$

### Получить все курсы
GET {{baseUrl}}/exchangeRates
Accept: application/json

### Получить курс по паре
GET {{baseUrl}}/exchangeRate/USDRUB
Accept: application/json

### Добавить курс
POST {{baseUrl}}/exchangeRates
Content-Type: application/x-www-form-urlencoded
Accept: application/json

baseCurrencyCode=JPY&targetCurrencyCode=EUR&rate=0.1234

### Обновить курс
PATCH {{baseUrl}}/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded
Accept: application/json

rate=1.234

### Конвертация валюты
GET {{baseUrl}}/exchange?from=USD&to=EUR&amount=10
Accept: application/json